### ISSUE TITLE
Compare node to xpath result

### ISSUE THREAD

**Issue by AndyGee** [xmlunit/user-guide#10]
I feel like I am trying to use this for the wrong reasons, but want to ask this question before I give up.

Given this snippet:

<?xml version="1.0" encoding="UTF-8"?><ORDER xmlns:xmime="http://www.w3.org/2005/05/xmlmime" version="3.0" type="standard">
  <ORDER_HEADER>
    <ORDER_INFO>
      <ORDER_ID>12345</ORDER_ID>

I would like to compare "<ORDER_ID>12345</ORDER_ID>" to the result of xpath "/ORDER/ORDER_HEADER/ORDER_INFO/ORDER_ID", ignoring the ns, encoding and attributes.

Is this possible without reinventing the wheel?

**Comment by bodewig** [comment]
I'm not sure I fully understand what you want to do.

Do you want to compare the `String` "<ORDER_ID>12345</ORDER_ID>" against the result of your XPath expression applied to the example document? If so you don't need the "<ORDER_ID>" brackets at all in your string as you know the element's name must be "ORDER_ID" or the XPath wouldn't return your result.

**Comment by bodewig** [comment]
any news?

**Comment by AndyGee** [comment]
Sorry for the noise. I can't even remember what this was about. I'll close.
