### ISSUE TITLE
Missing XML documentation for .NET classes and members

### ISSUE THREAD

**Issue by 0ndrej** [xmlunit/user-guide#11]
There is no XML documentation for .NET classes and members. It is needed to switch between VS and web browser just to read purpose of something in XMLUnit.

**Comment by bodewig** [comment]
They are inside the binary release archives (only in the Debug folder as I've just realized). I naively assumed XML docs would go to Symbolsource, seems I was wrong.

**Comment by bodewig** [comment]
I'll look into adding the xml docs to the nuget packages and making them available inside the release folder for the binaries as well. Will cut a new XMLUnit.NET release once I'm done.

**Comment by 0ndrej** [comment]
Thanks it will be very useful.

**Comment by bodewig** [comment]
May take a few days until I find some cycles, though.

**Comment by bodewig** [comment]
I've just released 2.3.1 the binary distribution and the nuget package should now contain the xml docs.
