### ISSUE TITLE
Similar XDocuments are considered different?

### ISSUE THREAD

**Issue by drauch** [xmlunit/user-guide#12]
I'm using the following code, explicitly stating I want to "check for similar", i.e., I don't want "similar" XDocuments to be considered different. According to your docs, child element order should not matter anymore in that case, but it does:

    // Shows differences for
    // actual = <Root><Elem/><Elem2/></Root>
    // expected = <Root><Elem2/><Elem/></Root>
    var diff = DiffBuilder
          .Compare(Input.FromDocument(actual))
          .WithTest(Input.FromDocument(expected))
          .CheckForSimilar()
          .Build()
          .Differences;

What am I doing wrong?

I'm using v2.5.

**Comment by bodewig** [comment]
Without knowing the documents this is hard to tell. Most likely XMLUnit doesn't know which elements of the control document to match with which element of the test document. You'll likely need to provide an [`ElementSelector`](https://github.com/xmlunit/user-guide/wiki/SelectingNodes).

**Comment by bodewig** [comment]
Sorry just now saw the documents are in the comment of your code.

```csharp
    .WithNodeMatcher(new DefaultNodeMatcher(ElementSelectors.ByName))
```

is probably enough.

**Comment by drauch** [comment]
Ok, thanks for the great answer. Can you tell me why these two are non-similar as well?

    // actual = <Root xmlns:x="http://ns.com"><x:Elem/></Root>
    // expected = <Root xmlns:y="http://ns.com"><y:Elem/></Root>

I want them to be detected as similar as well.

**Comment by bodewig** [comment]
I'd expect them to be as the prefix shouldn't make things "different". What is the difference reported?

**Comment by drauch** [comment]
// Actual = <Root xmlns:x=""http://namespace.com""><x:Elem></x:Elem><x:Elem2></x:Elem2></Root>
    // Expected = <Root xmlns:y=""http://namespace.com""><y:Elem></y:Elem><y:Elem2></y:Elem2></Root>

=>

    Expected element tag name 'x:Elem' but was 'y:Elem' - comparing <x:Elem...> at /Root[1]/Elem[1] to <y:Elem...> at /Root[1]/Elem[1] (DIFFERENT), Expected element tag name 'x:Elem2' but was 'y:Elem2' - comparing <x:Elem2...> at /Root[1]/Elem2[1] to <y:Elem2...> at /Root[1]/Elem2[1] (DIFFERENT)

**Comment by bodewig** [comment]
Oh, this looks like a bug.

https://github.com/xmlunit/xmlunit.net/blob/master/src/main/net-core/Diff/DOMDifferenceEngine.cs#L290 is supposed to compare the local names but it doesn't. The Java version is correct https://github.com/xmlunit/xmlunit/blob/master/xmlunit-core/src/main/java/org/xmlunit/diff/DOMDifferenceEngine.java#L333 .

I'm surprised (and shocked) there is no test catching this.

Could you please open a bug ticket for xmlunit.net and I'll look into fixing it the coming days? Or a PR if you feel like fixing it yourself ;-)

**Comment by drauch** [comment]
Reported it as https://github.com/xmlunit/xmlunit.net/issues/22

I know it can take some time to fix this, I currently do not have the time for a PR, sorry :-/ Many thanks to you though for a) maintaining such a useful library and b) answering question so quick. That's not a given and I respect that a lot 👍 🥇

**Comment by bodewig** [comment]
Thanks a lot for creating the report. No problem, finding the time to create the fix is the bigger problem here as well, I should be able to find some during the weekend.
