### ISSUE TITLE
How to compare soap xml with namespace

### ISSUE THREAD

**Issue by yhjhoo** [xmlunit/user-guide#15]
Consider following xmls, how to compare the content only?

```<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <soap:Body>
    <response>
          <IsNew>false</IsNew>
          <Dirty>true</Dirty>
          <gm xsi:nil="true"/>
    </response>
  </soap:Body>
</soap:Envelope>




<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<soap:Body>
  <ns2:response xmlns:ns2="http://tempuri.org/">
    <ns2:IsNew>false</ns2:IsNew>
    <ns2:Dirty>true</ns2:Dirty>
    <ns2:gm xsi:nil="true"/>
  </ns2:response>
</soap:Body>
</soap:Envelope>```

**Comment by bodewig** [comment]
Are you asking how to ignore the envelope or how to ignore the difference in namespaces?

If you are asking for the difference in namepaces, please understand they are very significant first. Two elements with the same local name but different namespace are as equal as two elements with different local names - not at all.

**Comment by yhjhoo** [comment]
These two xml can be considered the same, how to archieve in xmlunit? not sure about the terms in xmlunit

**Comment by bodewig** [comment]
From an XML point of view, they are not the same. If they happen to be the same for your application you need to 

1. downgrade differences of type `NAMESPACE_URI` to identical -> https://github.com/xmlunit/user-guide/wiki/DifferenceEvaluator
2. provide an `ElementSelector` that ignores the namespace URI. All built-in `ElementSelector`s are sensitive to the namespace URI, so you will have to write one of your own. -> https://github.com/xmlunit/user-guide/wiki/SelectingNodes - the interface/delegate is trivial to implement and if you look at the code of `ElementSelectors.byName` you will see how to write one that matches elements by their local name.
