### ISSUE TITLE
Wiki section about ValueAssert name wrong class

### ISSUE THREAD

**Issue by RalphEngelmann** [xmlunit/user-guide#16]
The section ["ValueAssert"](https://github.com/xmlunit/user-guide/wiki/XPath-Support#valueassert) on wiki page ["XPath Support"](https://github.com/xmlunit/user-guide/wiki/XPath-Support) has a confusing mistake:

> XMLUnit for Java 7+ provides an AssertJ assert class named ValueAssert that can be used to verify if the evaluation of the provided XPath expression meets certain conditions.
>
> Access to **MultipleNodeAssert** is provided by XmlAssert.valueByXPath(XPath).

It is not `MultipleNodeAssert` but `ValueAssert`

**Comment by bodewig** [comment]
Thanks! Fixed now.

You could have edited the page yourself, BTW.
