### ISSUE TITLE
Understanding `DefaultDifferenceEvaluator`

### ISSUE THREAD

**Issue by Varshaav16** [xmlunit/user-guide#17]
I am unable to understand [a different order of child nodes is handled as `SIMILAR`](https://github.com/xmlunit/user-guide/wiki/DifferenceEvaluator#default-differenceevaluator)

Is it like I have to pick the correct nodes using `ElementSelectors` and filters, only then the comparison will result in `SIMILAR`?

**Comment by bodewig** [comment]
Filters are there to logically remove elements completely, so once they are gone, they don't contribute to the outcome.

If XMLUnit is comparing two elements, then you've got three options

* for every child node of the control node there also is a child node of the test node that the current `ElementSelector` says are comparable. There is no child element in either control or test that was not matched to one on the other side. The order of child elements that will be compared is the same on both sides. This means things are IDENTICAL (unless there are other differences of course)
* for every child node of the control node there also is a child node of the test node that the current `ElementSelector` says are comparable. There is no child element in either control or test that was not matched to one on the other side. The order of child elements that will be compared is not the same on both sides. This means things are SIMILAR (unless there are other differences of course)
* there are child nodes in control that can not be comapred to any of the test children, or there are test children that can not be compared to any of the control children. Things are DIFFERENT.

But I'm afraid this is not what you are trying to ask. Maybe you can make your question more concrete with an example?

**Comment by Varshaav16** [comment]
Hey @bodewig thanks for your reply.
Example:
```java
public class XmlDemo {

    public static void main(String[] args) {

        String controlXml = "<struct>" +
                "<int>3</int>" +
                "<boolean>false</boolean>" +
                "</struct>";

        String testXml = "<struct>" +
                "<boolean>false</boolean>" +
                "<int>3</int>" +
                "</struct>";


        Diff diff = DiffBuilder.compare(controlXml)
                .withTest(testXml)
                .build();

        for (Difference difference : diff.getDifferences())
            System.out.println(difference);
    }

}
```

As the [documentation](https://github.com/xmlunit/user-guide/wiki/DifferenceEvaluator#default-differenceevaluator) says "a different order of child nodes is treated as `SIMILAR`, I am expecting the output to be similar, but the is the error message I got.

>Expected element tag name 'int' but was 'boolean' - comparing <int...> at /struct[1]/int[1] to <boolean...> at /struct[1]/boolean[1] (DIFFERENT)  
Expected text value '3' but was 'false' - comparing <int ...>3</int> at /struct[1]/int[1]/text()[1] to <boolean ...>false</boolean> at /struct[1]/boolean[1]/text()[1] (DIFFERENT)  
Expected element tag name 'boolean' but was 'int' - comparing <boolean...> at /struct[1]/boolean[1] to <int...> at /struct[1]/int[1] (DIFFERENT)  
Expected text value 'false' but was '3' - comparing <boolean ...>false</boolean> at /struct[1]/boolean[1]/text()[1] to <int ...>3</int> at /struct[1]/int[1]/text()[1] (DIFFERENT)  
This is what I am getting as the output.

I used `ElementSelectors.byNameAndText` to solve this issue, but I am not understanding why should we specify this as the docs already says child node order is treated as `SIMILAR`.

**Comment by Varshaav16** [comment]
I am just guessing, for `DefaultDifferenceEvaluator` to work as expected (to say that the two XML pieces are `SIMILAR`) `NodeMatcher` should choose the right pair of nodes and that's why we are using `ElementSelectors.byNameAndText`

**Comment by bodewig** [comment]
If you don't specify any `ElementSelector` at all, the default is to compare nodes in order. So yes, if you've got swapped elements then you will need an `ElementSelector` that helps XMLUnit to decide which child elements to combine with each other.

**Comment by bodewig** [comment]
see https://github.com/xmlunit/user-guide/wiki/SelectingNodes#elementselectorsdefault

**Comment by Varshaav16** [comment]
Thanks @bodewig
It would be great if you can add a note in `DefaultDifferenceEvaluator` ([here](https://github.com/xmlunit/user-guide/wiki/DifferenceEvaluator#default-differenceevaluator)) like this

>**Note** 
> The order of child nodes is consider as `SIMILAR` provided the `NodeMatcher` selects the **correct nodes** for comparison. As the `DefaultDifferenceEvaluator` uses `ElementSelectors.Default` for selecting the nodes.

**Comment by bodewig** [comment]
this is a Wiki and you've got write access ;-)

**Comment by Varshaav16** [comment]
added it

**Comment by bodewig** [comment]
thank you
