### ISSUE TITLE
Typo/mistake in wiki entry for "Default DifferenceEvaluator"

### ISSUE THREAD

**Issue by jhyot** [xmlunit/user-guide#2]
The wiki section https://github.com/xmlunit/user-guide/wiki/DifferenceEvaluator#default-differenceevaluator has this bullet item which has a mistake and makes no sence:
"different xsi:noNamspaceSchemaLocation and xsi:noNamspaceSchemaLocation"
- xsi:noNam**e**space...
- you have the same xsi: string twice.

**Comment by bodewig** [comment]
Yes, you are correct, one of them should have been `xsi:schemaLocation` - and is now.

Thanks!
