### ISSUE TITLE
Validator#setSchemaSource() not sufficient for resolving DTD

### ISSUE THREAD

**Issue by smillies** [xmlunit/user-guide#3]
[This code](https://github.com/xmlunit/user-guide/wiki/Validating-XML#validating-documents) for validating an XML document against some other schema than what is defined in the doctype declaration (we're talking DTD here) does not work in version 2.1.0. Because of the way ParsingValidator.Handler#resolveEntity() is written.

The following alternative version works for me, in which I set the systemId on the schema source:

```
Validator v = Validator.forLanguage(Languages.XML_DTD_NS_URI);
StreamSource dtd = new StreamSource(getClass().getResourceAsStream("/My.dtd"));
dtd.setSystemId(getClass().getResource("/My.dtd").toURI().toString());
v.setSchemaSource(dtd);
ValidationResult r = v.validateInstance(xmlDocument);
assertTrue(r.isValid());
```

-- Sebastian

**Comment by bodewig** [comment]
First of all thanks for the example, I'll add it to the user guide.

When you say the original example doesn't wok for DTDs "because of the way ParsingValidator.Handler#resolveEntity() is written" - can you suggest an alternative implementation that would work better?
