### ISSUE TITLE
Comparing similar XML showing differences

### ISSUE THREAD

**Issue by themese** [xmlunit/user-guide#5]
Hi, I've been trying XMLUnit for a few days and I was wondering if there is any certain way to show the differences between two similar xml files.

I'm currently using it for unit test purposes, so what I really want is to have a comparator that considers to xml files similar (when they do are similar), but that also can detect their differences. The default .CheckForSimilar() works fine, but if you debug the DiffBuilder object it won't any difference between two similar xml.

I'm new to C#, apologies in advance if there is any obvious way to do it and I just can't find it.
Regards,
Mese

**Comment by bodewig** [comment]
I'm not sure I understand what you want to do. If you've configured a `DiffBuilder` and created a `Diff` instance by invoking `Build()` on the builder, then `Diff`'s `Differences` property should hold all differences found - no matter whether the documents are different or similar.

**Comment by themese** [comment]
Sorry, perhaps I haven't expressed myself properly, thanks for the fast answer.

My problem is that I have two similar xml files, which they have slight differences (like having the same node, but in other order). The builder recognise them as similar, which is what I want, but when I call diff.Differences, the result is an empty array.

Is there any way of having those differences in Differences? Like having those different node order in that result array?

Hope I have explained myself better :)

Regards, 
Mese

**Comment by bodewig** [comment]
You mean `diff.HasDifferences` returns `true` but `diff.Differences` is empty? This is really strange, can you show how you use the builder and its result with a few lines of code?

**Comment by themese** [comment]
No, HasDifferences is indeed false and Differences is empty, because those differences are considered as similar. What I want is to still be considered as similar but returning those differences (if there is any possible way, of course).
Thanks again

**Comment by bodewig** [comment]
If you've set up `DiffBuilder` with `CheckForSimilar` the resulting `Diff` instance is supposed to hold the differences (which might be a bad name).

If this is not the case for you, then either something is not quite right in the way you configure `DiffBuilder` or you've found a bug. For the former we need to see you code, for the later I'd be grateful for a testcase ;-)

**Comment by themese** [comment]
Yes, I am using a DiffBuilder with CheckForSimilar, so I guess the differences are being held. My bad. It was really necessary for me to obtain those differences although being similar. I suppose I can always compare both files twice, one checking for similarities and another checking just for strict comparison.
Thanks for the quick replies, bodewig. Your project is helping me greatly, thanks. You can close this issue whenever you want :)

Regards, 
Mese

**Comment by bodewig** [comment]
If there is anything missing in the docs, I'd be grateful for a pointer. It's hard to detect the missing information when you know the code too well.

**Comment by themese** [comment]
I don't think there's anything missing more than me don't understanding the docs 100%

**Comment by bodewig** [comment]
Thank you.
