### ISSUE TITLE
Compare results are wrong if child node count is different in both the xml files.

### ISSUE THREAD

**Issue by ravipeta** [xmlunit/user-guide#6]
XML1
...................

```
<flowers>
<flower>Daisy</flower>
<flower>Roses</flower>
<flower>Daisy1</flower>
</flowers>
```

XML2
............................

```
<flowers>
<flower>Roses</flower>
<flower>Daisy1</flower>
</flowers>
```

```
 var myDiff = DiffBuilder.Compare(controlXml).WithTest(testXml).CheckForSimilar()
                  .WithNodeMatcher(new DefaultNodeMatcher(ElementSelectors.ByName)).Build();
```

**Expected difference is 1, but it is giving 4 differences.**

**Comment by bodewig** [comment]
Looking at you example I'd expect four differences. You specify `ElementSelector.ByName` so the `flower` elements are matched in order as they all have the same name.
- number of children of `flowers`
- text value of the first `flower` 
- text value of the second `flower`
- no match at all for the third `flower` in XML1

If you want to avoid the second and third difference,  you must use an `ElementSelector` that really selects what you want to match, likely `ElementSelector.ByNameAndText` - see https://github.com/xmlunit/user-guide/wiki/SelectingNodes#elementselectorsbynameandtext

If you want the comparison to stop as soon as the first difference has been encountered, you must use a non-default `ComparisonController`, likely `ComparisonController.StopWhenSimilar` - see https://github.com/xmlunit/user-guide/wiki/DiffBuilder#withcomparisoncontroller and http://www.xmlunit.org/api/net/2.2.0/Org.XmlUnit.Diff/ComparisonControllers.html

**Comment by bodewig** [comment]
Do we need to clarify anything?

**Comment by ravipeta** [comment]
thank you . it is working with ElementSelector.ByNameAndText.

But,

XML1
.................................

```
<flowers>
<flower>
<id>1</id>
<name>Daisy</name>
</flower>
<flower>
<id>2</id>
<name>Roses</name>
</flower>
<flower>
<id>3</id>
<name>Daisy1</name>
</flower>
</flowers>
```

XML2
..............................

```
**<flowers>
<flower>
<id>2</id>
<name>Roses</name>
</flower>
<flower>
<id>3</id>
<name>Daisy1</name>
</flower>
<flower>
<id>1</id>
<name>Daisy4</name>
</flower>
</flowers>**
```

Here i am expecting only 2 differences but it is showing 7 differences.

i have added one flower element on top 

```
**<flower>
<id>4</id>
<name>Daisy4</name>
</flower>**
```

here expecting two differences with added or deleted id 4 and name Daisy4.

Could you you help me out how to set ElementSelector as Node selector to should consider id of flower while comparing?

**Comment by bodewig** [comment]
`ByNameAndText` says "compare two elements, if their names match and their textual content - if any - does as well". This is not what you need, the identifying text that makes you pick the correct `flower` is not directly nested into the `flower` element.

Your case is exactly the same as the example in https://github.com/xmlunit/user-guide/wiki/SelectingNodes - replace `tr` with `flower` and `th` with `id`.

One solution is

``` csharp
ElementSelectors.ConditionalBuilder()
    .WhenElementIsNamed("flower").ThenUse(ElementSelectors.ByXPath("./id", ElementSelectors.ByNameAndText))
    .ElseUse(ElementSelectors.ByName)
    .Build();
```

assuming you are using XMLUnit.NET, otherwise lowercase the method names :-)

**Comment by ravipeta** [comment]
Thanks you for your update , it working as i expected.
and 
i came across another scenario which is not giving results as expected.

Compare :

```
<?xml version="1.0" encoding="utf-8" ?>
<Details>
  <Students>

    <Student>
      <Id>2</Id>
      <Name>RK</Name>
      <Marks>
        <English>90</English>
        <Maths>100</Maths>
        <Science>95</Science>
      </Marks>
    </Student>
    <Student>
      <Id>1</Id>
      <Name>sample</Name>
      <Marks>
        <English>90</English>
        <Maths>100</Maths>
        <Science>95</Science>
      </Marks>
    </Student>

  </Students>
</Details>
```

Test 

```
<Details>
  <Students>
    <Student>
      <Id>1</Id>
      <Name>sample1</Name>

    </Student>
    <Student>
      <Id>2</Id>
      <Name>RK</Name>
      <Marks>
        <English>90</English>
        <Maths>100</Maths>
        <Science>95</Science>
      </Marks>
    </Student>
  </Students>
</Details>
```

```
 var selector = ElementSelectors.ConditionalBuilder().WhenElementIsNamed("Student").ThenUse(ElementSelectors.ByXPath("./Id", ElementSelectors.ByNameAndText))
            .ElseUse(ElementSelectors.ByNameAndAllAttributes).Build();
            var result = DiffBuilder.Compare(compare).WithTest(test).CheckForSimilar().WithNodeMatcher(new DefaultNodeMatcher(selector)).Build();

```

Expected Result 

```
<English> missing
<Maths>missing
 <Science>missing
```

Actual Result

{Expected child 'Marks' but was '' - comparing <Marks...> at /Details[1]/Students[1]/Student[2]/Marks[1] to <NULL> (DIFFERENT)}

**Comment by bodewig** [comment]
I don't see any `Marks` element for `Student` with `Id` 1 in your test XML, so XMLUnit will complain it is not there. Why do you expect it to whine about the children of the non-existent node?

**Comment by ravipeta** [comment]
Thank you for your quick reply.

I am ok with what XMLUnit is resulting.
Just i want to know , is there any option i can inject to get children of missing node till lower depth instead of writing my own logic.

Thank you.

**Comment by bodewig** [comment]
Sorry if I sounded rude, that was not my intention.

When XMLUnit reports the `Marks` element to be missing, it will give you the `Marks` `(Xml)Node` as `target` of the comparison. You can walk the tree from there. There is no built-in way to have XMLUnit issue `Difference`s for the children of missing nodes as well.

**Comment by ravipeta** [comment]
Ok. thank you for your support.
