### ISSUE TITLE
Nested child nodes order not being ignored

### ISSUE THREAD

**Issue by krisrr3** [xmlunit/user-guide#7]
Hi guys,

```
I am trying to compare 2 XMLs and most of my scenarios are working except when the child nodes order are changed


          `Source expectedSource = Input.fromString(expectedMessage.getBphMessage()).build();
    Source outputSource = Input.fromString(actual.getBphMessage()).build();
    Diff diff = DiffBuilder.compare(expectedSource)
              .withTest(outputSource)
              .checkForSimilar()
              .withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.or(ElementSelectors.byNameAndText, ElementSelectors.byName)))
              .ignoreWhitespace()
              .build();

    if (diff.getDifferences() != null) {
        Iterator<Difference> it =  diff.getDifferences().iterator();

        while (it.hasNext()) {
            LOGGER.info("Difference : " + it.next().getComparison().toString());
        }

    }
    Assert.assertFalse(diff.toString(), diff.hasDifferences());`
```

XML1

---

`</sequenceB><sequenceC><F16R>SUXXXX</F16R><F19A>XXXX//XXXX1,</F19A><F22H>XXXA//XXXX</F22H><F19A>XXXG//2,46</F19A><F19A>XXXR//2,46</F19A><F19A>XXXA//100,00</F19A>`

XML2

---

`</sequenceB><sequenceC><F16R>SUXXXX</F16R><F19A>XXXG//2,46</F19A><F19A>XXXR//2,46</F19A><F19A>XXXX//XXXX1,</F19A><F22H>XXXA//XXXX</F22H><F19A>XXXA//100,00</F19A>`

 The message is longer than that and I can see the logs printing a number of differences. If I change the order of the child elements, it works fine.

Tried quite a lot of combinations with the ElementSelectors, but nothing seems to work. I am wondering whether I should be sorting the nodes before the comparison.

Thanks for helping out.
Kris

**Comment by bodewig** [comment]
Using `ElementSelector` is the XMLUnit way, there should be no reason to sort the notes.

My guess is that you get bitten by the way `or` works, see the second paragraph in https://github.com/xmlunit/user-guide/wiki/SelectingNodes#elementselectorsnot-and-or-and-xor 

Using your example, when you reach the first pair of `F19A`s they are first compared for element name and nested text, which fails, and then compared for element name only - before trying any other permutation of elements - which matches. What you want to use is the vararg constructor of `DefaultNodeMatcher`. Does 

``` java
.withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.byNameAndText, ElementSelectors.byName))
```

work?

**Comment by krisrr3** [comment]
Honestly I thought I had already tried this option. But this actually works....checked my other unit test scenarios and there are does not seem to be any regression.

Thanks
Kris

**Comment by bodewig** [comment]
Glad it worked.
