### ISSUE TITLE
Compare xml ignoring nested order

### ISSUE THREAD

**Issue by asifmom** [xmlunit/user-guide#8]
Consider following xmls

**First xml**
```
<ProfileHistory>
    <HistoryEvent>
        <Details><![CDATA[First]]></Details>
    </HistoryEvent>
    <HistoryEvent>
        <Details><![CDATA[Second]]></Details>
    </HistoryEvent>
</ProfileHistory>

```

**Second xml**
```
<ProfileHistory>
    <HistoryEvent>
        <Details><![CDATA[Second]]></Details>
    </HistoryEvent>
    <HistoryEvent>
        <Details><![CDATA[First]]></Details>
    </HistoryEvent>
</ProfileHistory>

```

As a user, I should have a provision to ignore order (in this case nested order)

`withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.byNameAndText))` doesn't work in this case. Let me know how this can be acheived.

**Comment by bodewig** [comment]
`byNameAndText` can't work as it would only help if you were comparing the `Details` nodes. What you really want to do is pick the correct branch when looking at the `HistoryEvent` nodes.

Please look through https://github.com/xmlunit/user-guide/wiki/SelectingNodes for more details as your case really is the same as the `table` example over there (replace `tr` with `HistoryEvent` and `th` with `Details`. There are several solutions outlined, the one I'd pick is something like

```
ElementSelectors.conditionalBuilder()
    .whenElementIsNamed("HistoryEvent").thenUse(ElementSelectors.byXPath("./Details", ElementSelectors.byNameAndText))
    .elseUse(ElementSelectors.byName)
    .build();
```

**Comment by asifmom** [comment]
Thanks for the help. It worked. However I needed to do a minor tweak to get it working for the following scenario:

Consider following xmls

**First xml**

```
<ProfileHistory>
    <HistoryEvent>
        <Details><![CDATA[First]]></Details>
        <Details><![CDATA[Third]]></Details>
    </HistoryEvent>
    <HistoryEvent>
        <Details><![CDATA[Second]]></Details>
        <Details><![CDATA[Four]]></Details>
    </HistoryEvent>
</ProfileHistory>
```

**Second xml**

```
<ProfileHistory>
    <HistoryEvent>
        <Details><![CDATA[Third]]></Details>
        <Details><![CDATA[First]]></Details>
    </HistoryEvent>
    <HistoryEvent>
        <Details><![CDATA[Four]]></Details>
        <Details><![CDATA[Second]]></Details>
    </HistoryEvent>
</ProfileHistory>
```

The code is 
`
ElementSelectors.conditionalBuilder()
.whenElementIsNamed("HistoryEvent")
.thenUse(ElementSelectors.byXPath("./Details",ElementSelectos.byNameAndText))
.elseUse(ElementSelectors.byNameAndText)
.build`

**Comment by bodewig** [comment]
Nice. I'm glad it works for you.
